app/bbs/views/bbs.py
from flask import Blueprint, Flask, request, render_template, redirect, url_for, session

import json
from datetime import datetime, timedelta
from flask_sqlalchemy import SQLAlchemy
from flask import request
from flask import jsonify
import ipwhois
import hashlib
from sqlalchemy import and_, or_

import psycopg2
import configparser

from flask import Markup
from ipwhois import IPWhois
from bbs.models import db
from bbs.models.bbs import Article, Thread, Board, Category
import os
import re
import errno
from enum import Enum, IntEnum, auto

THREAD_FIRST_POST = 1
THREAD_LAST_POST = 1000

DATA_USER = os.environ['DATABASE_USER']
DATA_PASS = os.environ['DATABASE_PASS']
DATA_HOST = os.environ['DATABASE_HOST']
DATA_NAME = os.environ['DATABASE_NAME']

bbs = Blueprint('bbs', __name__)

Hex_list = \
['0','1','2','3','4','5','6','7','8','9','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o',\
 'p','q','r','s','t','u','v','w','x','y','z','A','B','C','D','E','F','G','H','I','J','K','L','M','N',\
 'O','P','Q','R','S','T','U','V','W','X','Y','Z']

class atcl(IntEnum):
    id = 0
    article_count = auto()
    pub_date = auto()
    userid = auto()
    name = auto()
    article = auto()
    thread_id = auto()

@bbs.route("/")
def main():
    category_list, board_list = board_menu_imt()
    threads = Thread.query.all()
    return render_template("index.html", threads = threads, categories = category_list, boards = board_list)

@bbs.route("/search_result", methods=["GET"])
def search():
    search_get = request.args.get("search")
    notstr = '' 
    if search_get == notstr:
       return redirect("/")

    search_get = "%{}%".format(search_get) 
    search_hit = Thread.query.filter(Thread.threadname.like(search_get)).all()
    search_list = []
    for seth in search_hit:
       search_list.append(seth.threadname)
    
    return render_template("search_result.html",search=search_list)

@bbs.route("/thread_json/<thread_get>/<range_nmb>", methods=["POST"])
def thred_json_return(thread_get,range_nmb):
    if thread_search(thread_get) == False:
        return "not exist thread"
    thread = thread_search(thread_get) 
    return_article = article_acq(mode="ONLY_NUM", thread_arg = thread, range1 = range_nmb)
    
    for r in return_article:
        rejson = {
                    "Article": {
                        "id": r.id, 
                        "article_count": r.article_count, 
                        "pub_date": str(r.pub_date), 
                        "userid": r.userid, 
                        "name": r.name, 
                        "article": r.article
                        }
                 }
    #e = json.dumps(rejson)
    return jsonify(rejson)

@bbs.route("/create", methods=["POST"])
def create():
    thread_list = []
    threads = Thread.query.all()
    date = datetime.now()
    thread_get = request.form["thread"]
    article = request.form["article"]
    name = request.form["name"]
    userid = shorthash(((request.remote_addr[1] + date.strftime('%Y%m%d'))),8)
    message = ""
    article_count_first = 1
    name = threadpost_name_check(thread=thread_get, name=name)
    
    session['date'] = date
    session['article'] = request.form["article"]
    session['userid'] = shorthash((request.remote_addr[1] + date.strftime('%Y%m%d')),8)
    session['name'] = name

    for th in threads:
        thread_list.append(th.threadname)

    if thread_get in thread_list:
        thread = Thread.query.filter_by(threadname=thread_get).first()
        article_count = Article.query.filter_by(thread_id=thread.id).count() + 1
        session['article_count'] = article_count
        session['thread'] = thread

        if(threadpost_error_check(thread=thread_get, article_count=article_count, article=article, name=name, date=date, userid=userid)):
            message = threadpost_error_log(thread=thread_get, article_count=article_count, article=article, name=name, date=date, userid=userid)
            session['message'] = message
            return redirect(url_for('bbs.error_direct'))

        admin = Article(article_count, pub_date=date, name=name, article=article, userid=userid, thread_id=thread.id)
        db.session.add(admin)
        db.session.commit()
        articles = article_acq(mode="ALL", thread_arg=thread)
        return redirect(url_for('bbs.result_direct'))

    else:
        board_id = request.form["board_id"]
        thread_new = Thread(thread_get,board_id)

        if(threadpost_error_check(thread=thread_get, article_count=article_count_first, article=article, name=name, date=date, userid=userid)):
            message = threadpost_error_log(thread=thread_get, article_count=article_count_first, article=article, name=name, date=date, userid=userid)
            session['message'] = message
            return redirect(url_for('bbs.error_direct'))

        db.session.add(thread_new)
        db.session.commit()

        thread = Thread.query.filter_by(threadname=thread_get).first()
        article_count = Article.query.filter_by(thread_id=thread.id).count() + 1
        session['thread'] = thread.threadname
        session['article_count'] = article_count

        admin = Article(article_count, pub_date=date, name=name, article=article, userid=userid, thread_id=thread.id)
        db.session.add(admin)
        db.session.commit()
        #articles = article_acq(mode="ALL", thread_arg=thread_new)
        return redirect(url_for('bbs.result_direct_thread'))

@bbs.route("/result_direct_thread/")
def result_direct_thread():
    if 'article_count' not in session and 'article' not in session and 'name' not in session and 'date' not in session and 'thread' not in session and 'userid' not in session:
        return redirect(url_for('/'))
    
    date = session['date']
    article = session['article']
    name    = session['name']
    userid = session['userid']
    thread = session['thread'] 
    thread = Thread.query.filter_by(threadname=thread).first()
    article_count = session['article_count'] 

    return render_template("bbs_result.html", article_count=article_count, article=article, name=name, now=date,thread=thread, userid=userid, threadinit='True')


@bbs.route("/thread/<thread_get>/")
def thread_defo(thread_get):
    return thread(thread_get,"dummy")

@bbs.route("/thread/<thread_get>/<range_nmb>")
def thread(thread_get,range_nmb):
    thread_list = []
    start_point_temp = []
    
    threads = Thread.query.all()
    for th in threads:
        thread_list.append(th.threadname)
    if thread_get in thread_list:
        thread = Thread.query.filter_by(threadname=thread_get).first()
    else:
        print("error")
        return render_template("index.html")
    
    start_point_temp.append(range_nmb.find('l')) if range_nmb.find('l') >= 0 else False
    start_if_number = ((re.search('.*\d.*',range_nmb).start())) if re.search('.*\d.*',range_nmb) != None else False
    start_point_temp.append(range_nmb.find('-')) if range_nmb.find('-') >= 0 else False
    
    if  start_point_temp != [] and start_if_number != None:
        if min(start_point_temp) > start_if_number  and range_nmb[min(start_point_temp)] != '-':
            start_point_temp.append((re.search('.*\d.*',range_nmb).start()))

    else:
        start_point_temp.append(0)

    start_point = min(start_point_temp)
    
    bo = Board.query.filter_by(id=thread.board_id).first()

    if range_nmb[start_point] == 'l':
        range_temp1 = range_nmb.split('-')
        range_temp = range_temp1[0].split('l')
        if re.sub(r"\D","",range_temp[1]) == None or len(re.sub(r"\D","",range_temp[1])) == 0:
            articles = article_acq(mode="ALL", thread_arg = thread)

        else:
            display_range = int(re.sub(r"\D","",range_temp[1]))
            articles = article_acq(mode="L", thread_arg=thread, range1=display_range)
            
    elif range_nmb[start_point] == '-':
        range_temp1 = range_nmb.split('l')
        range_temp = range_temp1[0].split('-')
        display_range_start = THREAD_FIRST_POST      
        display_range_end = THREAD_LAST_POST     
        
        if ((range_temp[0] is not None) and (not len(range_temp[0]) == 0)):
            display_range_start = int(re.sub(r"\D","",range_temp[0]))
        
        if ((range_temp[1] is not None) and (not len(range_temp[1]) == 0)):
            display_range_end = int(re.sub(r"\D","",range_temp[1]))     
        
        if display_range_start == THREAD_FIRST_POST and display_range_end == THREAD_LAST_POST:
            articles = article_acq(mode="ALL", thread_arg = thread)

        else:
            articles = article_acq(mode="-", thread_arg=thread, range1=display_range_start, range2=display_range_end)
    
    else:
        range_temp1 = range_nmb.split('-')
        range_temp = range_temp1[0].split('l')
        
        if len(re.sub(r"\D","",range_temp[0])) == 0:
            articles = article_acq(mode="ALL", thread_arg = thread)
        
        else:
            display_range = int(re.sub(r"\D","",range_temp[0]))
            articles = article_acq(mode="ONLY_NUM", thread_arg = thread, range1 = display_range)
    
    if len(articles) == 0:
        return redirect(url_for('bbs.thread_defo', thread_get=thread_get))

    return render_template("thread.html",
                             articles=articles,
                             thread=thread_get,
                             board=bo
                             )


@bbs.route("/result", methods=["POST"])
def result():
    date = datetime.now()
    session['date'] = date
    session['article'] = request.form["article"]
    session['userid'] = shorthash((request.remote_addr[1] + date.strftime('%Y%m%d')),8)
    session['thread'] = request.form["thread"]
    thread = Thread.query.filter_by(threadname=(request.form["thread"])).first()
    session['article_count'] = Article.query.filter_by(thread_id=thread.id).count() + 1

    date = datetime.now()
    article = request.form["article"]
    name = request.form["name"]

app/templates/aritcle_template.html
        <div class="post">
            <a name="article"{{ article.article_count }}>
            <span class="number">{{ article.article_count }}</span>
            </a>
            <b>
                <span class="name">{{ article.name }}</span>
            </b>
            <span class="date">{{ article.pub_date }}</span>
            <span class="uid">   ID:{{ article.userid }}</span>

        <div class="message">
            <span class="article">
                <script src=" {{url_for('static', filename='js/article.js')}} "></script>
                <div id="article{{ article.article_count }}"></div>
                <script type="text/javascript">
                    var article = `{{ article.article }}`;
                    var article_count = `{{ article.article_count }}`
                    var thread = `{{ thread }}`;
                    res_read(article);
                </script>
            </span>
        </div>
    </div>
    <br>
    {% block content %}
    {% endblock %}

app/templates/bbs_error.html
{% extends "layout.html" %}
{% block content %}
<h1>エラー</h1>
<br>
<div class="thread_thread">
    <div class="post">
        <span class="number">{{ article_count }}</span>
        <b>
            <span class="name">{{ name }}</span>
        </b>
        <span class="date">{{ now }}</span>
        <span class="uid"> ID:{{ userid }}</span>

        <div class="message">
            <span class="article">
                <div id="article{{ article_count }}">{{ article }}</div>
            </span>
        </div>
    </div>

    <pre><p>{{ message }}</p></pre>

    <script type="text/javascript">

        // 一定時間経過後に指定ページにジャンプする
        waitTimer = 1000; // 何秒後に移動する

        url = "{{ url_for('bbs.thread',thread_get=thread.threadname,range_nmb="l50") }}"; // 移動するアドレス

        if ("{{ thread.threadname }}" === "") {
            url = "{{ url_for('bbs.main') }}"; // 移動するアドレス
        }

        function jumpPage() {
            location.href = url;
        }
        setTimeout("jumpPage()", waitTimer * 1000)
    //-->
    </script>

    {% if not thread.threadname %}
    <br>
    1000秒後にメインページへ移動します
    <br>

    {% else %}
    <br>
    1000秒後にスレッドへ移動します
    <br>

    {% endif %}


    {% if not thread.threadname %}
    {% else %}
    <form action="/thread/{{ thread.threadname }}/l50" method="get">
        <button type="submit">スレへ戻る</button>
    </form>
    {% endif %}


    <form action="/" method="get">
        <button type="submit">HPに戻る</button>
    </form>

    <button type="button" onclick="history.back()">前のページに戻る</button>

    {% endblock %}

app/templates/bbs_result.html
{% extends "layout.html" %}
{% block content %}
<h1>書き込みました</h1>
<br>
<div class="thread_thread">
    <div class="post">
        <span class="number">{{ article_count }}</span>
        <b>
            <span class="name">{{ name }}</span>
        </b>
        <span class="date">{{ now }}</span>
        <span class="uid"> ID:{{ userid }}</span>

        <div class="message">
            <span class="article">
                <div id="article{{ article_count }}">{{ article }}</div>
            </span>
        </div>
    </div>
</div>

{% if threadinit == 'True' %}
<br>
<br>
<pre><p>スレッドが作成できました</p></pre>
<pre><p>スレッド名　{{ thread.threadname }}</p></pre>
{% else %}
{% endif %}



<script type="text/javascript">
    // 一定時間経過後に指定ページにジャンプする
    waitTimer = 5; // 何秒後に移動する
    url = "{{ url_for('bbs.thread',thread_get=thread.threadname,range_nmb="l50") }}"; // 移動するアドレス
    function jumpPage() {
        location.href = url;
    }
    setTimeout("jumpPage()", waitTimer * 1000)
    //-->
</script>

<br>
5秒後にスレッドへ移動します
<br>


<form action="/" method="get">
    <button type="submit">戻る</button>
</form>
{% endblock %}

app/templates/board.html
{% extends "layout.html" %}
{% block content %}
<script src=" {{url_for('static', filename='js/article.js')}} "></script>

    <h1>5.2ちゃんねる</h1>

        <div class="HEADER_AREA">
            <h2>
               <span class="board_top">{{ boards.boardname }}</span>
            </h2>
            <div class="board_reader">
            </div>

            <hr size="10" color="white">

            <div class="SPARROW">
            <h3 style="margin: 0; padding: 0; text-align: left;">この板の投稿数順位</h3>
            <p style="margin: 0px; padding: 0px; font-size: 0.75em; color: rgb(51, 102, 102); text-align: left; --darkreader-inline-color:#96caca;" data-darkreader-inline-color="">最終更新日時：????/??/?? ??:??:??</p>
            <p style="margin: 0; padding: 0; white-space: nowrap; text-align: left;">本日の総投稿数：
                <span style="color: rgb(204, 51, 51); --darkreader-inline-color:#d14747;" data-darkreader-inline-color> ?</span>
                  順位：
                <span style="color: rgb(204, 51, 51); --darkreader-inline-color:#d14747;" data-darkreader-inline-color> ???/?,???</span>
            </p>
            <p style="margin: 0; padding: 0; white-space: nowrap; text-align: left;">分あたり投稿数：
                <span style="color: rgb(204, 51, 51); --darkreader-inline-color:#d14747;" data-darkreader-inline-color> ?</span>
                  順位：
                <span style="color: rgb(204, 51, 51); --darkreader-inline-color:#d14747;" data-darkreader-inline-color> ???/?,???</span>
            </p>
            <p style="margin: 0; padding: 0; text-align: right;"><a href="//stat.5ch.net/SPARROW/">SPARROW</a></p>
            </div>
            
            
            <h3><span class="common">ご案内</span></h3>
            <p style="margin: 0; padding: 0 0.5em 0.5em 0.5em; text-align: left; font-size: 0.75em; font-weight: bold;">
                <a href="dummy.html">書き込む前に読んでね</a><br>
                <a href="dummy.html">５.２ちゃんねるガイド</a><br>
                <a href="#menu">この板の主なスレッド一覧</a><br>
                <a href="#0">１番目のスレッド</a>
                </p>
        </div>
    <div class="THREAD_MENU">
        <h3>
            <a name="menu"></a>
            <span class="common">この板の主なスレッド</span>
        </h3>

        <p style="margin: 0; padding: 0 0 0.5em 0.5em; font-size: 0.75em;">
            <b>
                <a href="dummy.html">スレッド一覧はこちら</a>
                <a href="dummy.html">過去ログ一覧はこちら</a>
            </b>
        </p>
        
        <div class="THREAD_LIST">
            {% set ns = namespace(cnt = 1) %}
            {% for thread in threads: %}
                <a href="{{ url_for('bbs.thread_defo',thread_get=thread) }}">{{ ns.cnt }}: </a>
                <a href="#{{ ns.cnt - 1 }}">{{ thread }}</a>
                <br>
                {% set ns.cnt = ns.cnt + 1 %}
            {% endfor %}
        </div>

        <p style="margin: 0; padding: 0.5em 0 0.5em 0.5em; font-size: 0.75em;">
            <b>
                <a href="#new_thread">新規スレッド作成はこちら</a>
            </b>
        </p>
        <p style="margin: 0; padding: 0 0 0.5em 0.5em; font-size: 0.75em;">
            <b>
                <a href="subback.html">スレッド全一覧はこちら</a> 
                <a href="kako/kako0000.html">過去ログ一覧はこちら</a>
            </b>
        </p>
    </div>
    
    {% set ns = namespace(cnt = 1) %}
    {% for thread in threads: %}

    <div class="THREAD_CONTENT">
        <div class="THREAD_IN">
            <a href="#menu">目</a>
            <a href="#{{ next_jp[ns.cnt - 1] }}">次</a>
            <a href="#{{ prev_jp[ns.cnt - 1] }}">前</a>
            <a href="#new_threa">新</a>
        </div>
        
        <div class="RES_NUMBER">
            <span class="RES">
                {{ ns.cnt }}：{{ a_to[ns.cnt - 1] }}
                <span style="font-size: 0.75em;">レス</span>
            </span>

            <span>
                CP:??
            </span>
        </div>

        <h3 class="thread_title" style="margin: 0; padding: 0 2.0em 0 3.0em; text-indent: -4.0em;">
            <span style="padding: 0px 0px 1.5em 1em; color: rgb(255, 0, 0); font-size: 1.0em; --darkreader-inline-color:#ff1a1a;">{{ thread }}</span>
            <a name="{{ ns.cnt - 1 }}"></a>
        </h3>
        
        {% for article in articles[ns.cnt]: %}

        <dl class="thread" style="margin-top: 0px;">
            <dt>{{ article.article_count }}  名前：
                <span>
                    <b>{{ article.name }}</b>
                </span>

                {{ article.pub_date }}

                <small></small>

               ID：{{ article.userid }}
            </dt>

            <dd style="margin-bottom: 2.0em; font-size: 1.00em; margin-left:40px; font-weight: normal;">
                <div id="article{{ article.article_count }}"></div>
                    <script type="text/javascript">
                        var article = `{{ article.article }}`;
                        var article_count = `{{ article.article_count }}`
                        var thread = `{{ thread }}`; 
                        res_read();
                    </script>
            </dd>
        </dl>
        {% endfor %}
        {% set ns.cnt = ns.cnt + 1 %}
        
        <hr size="10" color="white">
        <p style="margin: 0; padding: 0.5em;">
        <a href="{{ url_for('bbs.thread_defo',thread_get=thread) }}">全部読む</a>    
        <a href="{{ url_for('bbs.thread',thread_get=thread,range_nmb="l50") }}">最新50</a>    
        <a href="{{ url_for('bbs.thread',thread_get=thread,range_nmb="1-100") }}">1-100</a>    
        <a href="#menu">この板の主なスレッド一覧</a>
        <a href="{{ url_for('bbs.board',board_name=boards.boardname) }}">リロード</a>
        </p>
        <hr size="10" color="white">
        
        <h3>
            <span class="common">書き込み欄</span>
        <h3>
        
        <form action="/result"  method="post">
            <p style="margin: 0 0 0 2em; font-size: 0.75em;">
                <input type="hidden" name="thread" value="{{ thread }}">
                <button type="submit">送信する</button> 
                <br>
                名前：<input type="text" name="name" style="width: 16em;">
                E-mail：<input type="text" name="mail" style="width: 16em;">
                <br>
                <textarea style="min-width: 40em; height: 10.0em; word-wrap: break-word;" 
                          name="article" rows="4" cols="12"></textarea>
                <br>
            </p>
        </form>
    </div> 
    {% endfor %}
   <div class="NEW_THREAD"> 
      <form action="/create" method="post">
          <a name="new_thread"></a>
          <h3>
              <span class="common">新規スレッド作成</span>
          </h3>
          
          <p style="margin: 0 0 0 2em; font-size: 0.75em;">
              <input type="submit" value="新規スレッド作成" name="submit">
              <br>
              スレッドタイトル
              <input type="text" name="thread" style="width: 24em;">
              <input type="hidden" name="board_id" value="{{ boards.id }}">
              <br>
              名前：<input type="text" name="name" style="width: 16em;">
              E-mail：<input type="text" name="mail" style="width: 16em;">
              <br>
              <textarea style="min-width: 40em; height: 10.0em; word-wrap: break-word;" 
                        name="article" rows="4" cols="12"></textarea>
          </p>
      </form>
   <div>
{% endblock %}

app/templates/board_menu.html
{% extends "layout.html" %}
{% block content %}
      {% for category in categories: %}
        {{ category }}
        {% for board in boards[loop.index]: %}
                <a href="{{ url_for('bbs.board',board_name=board.boardname) }}">{{ board.boardname }}</a>
        {% endfor %}
    {% endfor %}





{% endblock %}

app/templates/dummy.html
{% extends "layout.html" %}
{% block content %}
            <span class = "foo">
            
            <h1>5.2ちゃんねる</h1>
                        
            <p>作成中です。ごめんなさい。</p>
            
            </span>

{% endblock %}

app/templates/index.html
{% extends "layout.html" %}
{% block content %}
    <div id="wrapper">
        <div class="left-column">
            <a href="/board_menu">板一覧</a>
            <br>
            {% set ns = namespace(cnt = 1) %}
            {% for category in categories: %}
                {{ category }}
                <br>
                {% for board in boards[ns.cnt]: %}
                    <a href="{{ url_for('bbs.board',board_name=board.boardname) }}">{{ board.boardname }}</a>
                    <br>
                {% endfor %}
                {% set ns.cnt = ns.cnt + 1 %}
            {% endfor %}            
        </div>
        
        <div class="right-column">
            <span class = "foo">
            
            <h1>5.2ちゃんねる</h1>
            
            <p>
            <a href="/">TOP</a>
               - 
            <a href="dummy.html">GUIDE(FAQ)</a>
            </p>

            <p>
            「ハッキング」から「今晩のおかず」まで手広くカバーする巨大掲示板群
            <br>
            <strong style="font-size: 1.25em;">『５.２ちゃんねる』</strong>
            へようこそ!
            <br>
            <strong style="font-size: 1.25em;">『５.２ちゃんねる』</strong>
            って何?という方は
            <a href="/">インフォメーション</a>
            をご覧ください。
            </p>
    
            <p>
            <a href="/">浪人を買います</a>
            </p>

            <form action="/search_result" method="get">
                <label for="search">スレッド検索</label>
                <input type="text" name="search">
                <button type="submit">検索</button>
            </form>

            </span>

        <h2>スレッド一覧</h2>
            {% for thread in threads: %}
            <a href="{{ url_for('bbs.thread_defo',thread_get=thread.threadname) }}">{{ thread.threadname }}</a>
            <br>
            {% endfor %}
      </div>
  </div>

{% endblock %}

app/templates/search_no_result.html
{% extends "layout.html" %}
{% block content %}
<h1>検索結果 何もなし</h1> 
{% endblock %}

app/templates/search_result.html
{% extends "layout.html" %}
{% block content %}
<h1>検索結果</h1> 

       {% if search %}
          {% for f in search: %}
              <form action="/thread" name="{{ f }}"  method="post">
              <input type="hidden" name="thread" value="{{ f }}">
              <a href="javascript:{{ f }}.submit()">{{ f }}</a>
         </form>
         {% endfor %}
       {% else %}
         <p>該当する検索結果は見つかりませんでした</p>
       {% endif %}
{% endblock %}

app/templates/test.html
{% extends "layout.html" %}
{% block content %}
            <span class = "foo">
            
            <h1>5ちゃんねる</h1>
            <p>{{ test }}</p>
                        
            <p>testです</p>
            
            </span>

{% endblock %}

app/templates/thread.html
{% extends "layout.html" %}
{% block content %}
<script src=" {{url_for('static', filename='js/article.js')}} "></script>

<h1>掲示板</h1>
<div class="THREAD_ALL">
    <h1 class="TITLE">
        {{ thread }}
    </h1>
    
    <div class="pagestats">
        <ul class="menujust">
            <li class="metastats">
                {{ thread }} コメント
            </li>
        </ul>
    </div>

    <div class="topnav">
        <ul class="menujst">
            <li class="menu_topnav">
                <a class="menuitem" href="{{ url_for('bbs.thread_defo',thread_get=thread) }}">全部</a>
            <li class="menu_topnav">
                <a class="menuitem" href="{{ url_for('bbs.thread',thread_get=thread,range_nmb="1-100") }}">1-100</a>
            <li class="menu_topnav">
                <a class="menuitem" href="{{ url_for('bbs.thread',thread_get=thread,range_nmb="l50") }}">最新50</a>
        </ul>
    </div>
    
    <div class="topnav">
        <ul class="menujst">
            <li class="menu_topnav">
                <a class="menuitem" href="{{ url_for('bbs.board',board_name=board.boardname) }}">掲示板に戻る</a>
        </ul>
    </div>
    <div class="thread_thread">
    {% for article in articles: %} 
        <div class="post">
            <span class="number">{{ article.article_count }}</span>
            </a>
            <b>
                <span class="name">{{ article.name }}</span>
            </b>
            <span class="date">{{ article.pub_date }}</span>
            <span class="uid">   ID:{{ article.userid }}</span>

        <div class="message">
            <span class="article">
                <div id="article{{ article.article_count }}"></div>
                <script type="text/javascript">
                    var article = `{{ article.article }}`;
                    var article_count = `{{ article.article_count }}`
                    var thread = `{{ thread }}`; 
                    res_read();
                </script>
            </span>
        </div>
    </div>    
    <br>
    {% endfor %}
</div>
    
<div class="topnav">
    <ul class="menujst">
        <li class="menu_topnav">
            <a class="menuitem" href="{{ url_for('bbs.thread_defo',thread_get=thread) }}">全部</a>
        <li class="menu_topnav">
            <a class="menuitem" href="{{ url_for('bbs.thread',thread_get=thread,range_nmb="1-100") }}">1-100</a>
        <li class="menu_topnav">
            <a class="menuitem" href="{{ url_for('bbs.thread',thread_get=thread,range_nmb="l50") }}">最新50</a>
    </ul>
</div>

<div class="topnav">
    <ul class="menujst">
        <li class="menu_topnav">
            <a class="menuitem" href="{{ url_for('bbs.board',board_name=board.boardname) }}">掲示板に戻る</a>
    </ul>
</div>

<div class="form_dayo">
    <span style="font-weight:bolder;">レスを投稿する</span>
    <hr>
    
    <form action="/result" method="post">
        <input class="form_post" size="70" name="name" placeholder="名前(省略可)">
        <br>
        <input class="form_post" size="70" name="name" placeholder="メールアドレス(省略可)">
        <br>
        <input type="hidden" name="thread" value="{{ thread }}">
        <textarea name="article" rows="5" cols="70" wrap="off" placeholder="コメント内容"></textarea>
        <br>
        <input type="submit" value="SUBMIT" name="submit">
    </form>
</div>

<form action="/" method="get">
    <button type="submit">戻る</button>
</form>

<div class="anker_tooltip"></div>
{% endblock %}